name: "Release"
on:
  push:
    paths:
      - 'thoth/__metadata__.py'

jobs:
  Pipeline:
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-22.04
    container: python:3.9

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: make requirements

    - name: Build package
      run: make package

    - name: Get version
      run: echo "version=$(make version)" >> $GITHUB_ENV

    - name: Get release notes
      id: get_release_notes
      uses: ffurrer2/extract-release-notes@v1

    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.version }}
        release_name: Release ${{ env.version }}
        body: ${{ steps.get_release_notes.outputs.release_notes }}

    - name: Release already exist
      if: ${{ failure() }}
      run: echo Release already exist

    - name: Publish release to pypi.org
      if: ${{ success() }}
      env:
        PYPI_USERNAME: __token__
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: python -m twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD --verbose dist/*
